apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer-deployment
spec:
  selector:
    matchLabels:
      app: java-producer
  template:
    metadata:
      labels:
        app: java-producer
    spec:
      containers:
      - name: producer
        image: producer
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
           name: mysql-secrets # Gets secrets for mysql user and password
        env:
        - name: SERVER_NAME
          value: mysql-service
        - name: PORT 
          value: "3306"
        - name: DATABASE_NAME
          value: test-application
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 300m #Request a minimum of 300 millicores. So the application will be deployed in a node which can assures this cpu request 
          limits:
            cpu: 500m #Limits the cpu utilization to 500 millicores. If the application exceeds this limit it will experiences throttling
        
