apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  type: NodePort
  ports:
  - port: 8080 #Port exposed by the Service
    targetPort: 8080 #Port of the Pod in which redirects the traffic
  selector:
    app: java-producer
