apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: ClusterIP
  ports:
  - port: 8080 #Port exposed by the Service
    targetPort: 8080 #Port of the Pod in which redirects the traffic
  selector:
    app: java-consumer
