apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306 #Port exposed by the Service
    targetPort: 3306 #Port of the Pod in which redirects the traffic
  selector:
    app: mysql
