#ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-application-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: test-application.7be81b3397d74077a3d1.eastus.aksapp.io #In azure "az network dns zone list --output table" copy ZoneName
      http:
        paths:
          - backend: # How the ingress will handle the requests
              serviceName: producer-service # Which service the request will be forwarded to
              servicePort: 8080 # Which port in that service
            path: /insert # Which path is this rule referring to
          - backend:
              serviceName: consumer-service
              servicePort: 8080
            path: /get(.*)
